#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
# Part of Dev CE, a fork of the Civilization VI Community Extension by Wild-W (https://github.com/Wild-W/CivilizationVI_CommunityExtension).
# Copyright (C) 2026 cru121. Licensed under the GNU Affero General Public License v3.0 (see LICENSE.txt). Not endorsed by Wild-W, Firaxis or 2K.
"""Split the functions that gen_bridge.py can expose from the whole gap list (--scope gap) into themed test sets.

    python dev-ce/tools/gen_bridge.py --scope gap --no-oracle --out dev-ce/data/plan/scratch_table.cpp --manifest dev-ce/data/plan/gap_exposed.json --skipped dev-ce/data/plan/gap_skipped.json
    python dev-ce/tools/make_sets.py

Writes dev-ce/data/sets/<set>.txt (one qualified C++ name per line, getters/checks included so that void mutators have a readback) and
dev-ce/data/sets/SETS.md (overview). Build a DLL with one or more sets:  python dev-ce/tools/gen_bridge.py --include set_b_influence,set_c_diplomacy
"""
import json, os, csv, collections

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
DEV = os.path.join(ROOT, 'dev-ce')
man = json.load(open(os.path.join(DEV, 'data', 'plan', 'gap_exposed.json'), encoding='utf-8'))
cat = {}
for r in csv.DictReader((l for l in open(os.path.join(ROOT, 'gap_list.tsv'), encoding='utf-8') if not l.startswith('#')), delimiter='\t'):
    cat[r['class'] + '::' + r['function']] = r['category']

SETS = [   # (file, title, interfaces, why)
    ('set_b_influence', 'City-state influence (rest of Player::Influence)', ['IPlayerInfluence'], 'envoy tokens, suzerain, levy, open borders: readbacks for the 16 mutators already in the base build'),
    ('set_c_diplomacy', 'Diplomacy', ['IPlayerDiplomacy', 'IGameDiplomacy', 'IDeal', 'IDealItem'], 'war weariness, grievances, pending actions, open borders, deals'),
    ('set_d_culture_religion', 'Culture, religion, stats, great people points', ['IPlayerCulture', 'IPlayerReligion', 'IPlayerStats', 'IPlayerGreatPeoplePoints', 'IGameReligion', 'IPlayerEras'], 'civics/policies, pantheons/beliefs, score statistics'),
    ('set_e_city', 'City internals', ['ICity', 'ICityBuildQueue', 'ICityBuildings', 'ICityGrowth', 'ICityCitizens', 'ICityReligion', 'ICityDistricts', 'IDistrict'], 'production queue, growth, citizens, buildings'),
    ('set_f_player', 'Player root and economy', ['IPlayer', 'IPlayerUnits', 'IPlayerResources', 'IPlayerTreasury', 'IPlayerTechs', 'IPlayerTrade', 'IPlayerCities', 'IPlayerGovernors', 'IPlayerWMDs'], 'player-wide switches, resources, treasury, techs, trade slots'),
    ('set_g_world', 'Game, map and world systems', ['IGame', 'IGameEras', 'IGameGreatPeople', 'IGameFalloutManager', 'IMap', 'IMapPlot', 'IMapTerritory', 'IMapAreaPortal', 'ITradeManager', 'IBarbarianTribes', 'IFreeCities'], 'global game state, eras, climate/fallout, barbarians, trade manager'),
    ('set_h_unit', 'Units', ['IUnit', 'IUnitExperience', 'IUnitGreatPerson', 'IUnitReligion'], 'unit state, experience, great person, religion'),
]
os.makedirs(os.path.join(DEV, 'data', 'sets'), exist_ok=True)
by = collections.defaultdict(list)
for e in man:
    by[e['iface']].append(e)
used = set()
md = ['# Dev CE test sets (generated by make_sets.py)', '',
      'Each set is a list of C++ functions the bridge generator can expose (scalar arguments, resolvable `this`, no name collision). Getters and checks are included',
      'so that void mutators have a readback. **Nothing here has been read or tested**: names and signatures come from the Linux debug symbols, the meaning is unknown.',
      'Build with `python dev-ce/tools/gen_bridge.py --include <set>[,<set>...]` (the base build is the 350 ranked candidates).', '',
      '| set | interfaces | functions | mutators | getters/checks | note |', '|---|---|---|---|---|---|']
for name, title, ifs, why in SETS:
    names = []
    nm = ng = 0
    for i in ifs:
        for e in by.get(i, []):
            q = e['cpp'].replace('GameCore::', '', 1)
            names.append(q)
            used.add(q)
            if cat.get(q) == 'mutator':
                nm += 1
            else:
                ng += 1
    with open(os.path.join(DEV, 'data', 'sets', name + '.txt'), 'w', encoding='utf-8') as f:
        f.write('# %s: %s\n# interfaces: %s\n' % (name, title, ', '.join(ifs)))
        for q in sorted(names):
            f.write(q + '\n')
    md.append('| %s | %s | %d | %d | %d | %s |' % (name, ', '.join(ifs), len(names), nm, ng, why))
for name, why in [('set_i_eras', 'hand-written: the Eras transition/commemoration functions decompiled on 2026-10-06 (findings/topics/eras-transition-and-commemorations.md)')]:
    p = os.path.join(DEV, 'data', 'sets', name + '.txt')
    if os.path.exists(p):
        n = [l for l in open(p, encoding='utf-8') if l.strip() and not l.startswith('#')]
        md.append('| %s | IGameEras, IPlayerEras | %d | - | - | %s |' % (name, len(n), why))
rest = [e for e in man if e['cpp'].replace('GameCore::', '', 1) not in used]
md += ['', 'Not in any set (%d): %s' % (len(rest), ', '.join(sorted({e['iface'] for e in rest})) or 'none')]
open(os.path.join(DEV, 'data', 'sets', 'SETS.md'), 'w', encoding='utf-8').write('\n'.join(md) + '\n')
print('\n'.join(md))
